# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- prod
- uat

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'prod') }}:
    buildConfiguration: production
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    buildConfiguration: development
  ${{ if eq(variables['Build.SourceBranchName'], 'uat') }}:
    buildConfiguration: uat

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration=${configuration}
  workingDirectory: $(Build.SourcesDirectory)/NSI.UI
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/NSI.UI/dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: Angular'
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
